services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5443:5432
    environment:
      POSTGRES_USER: Bath
      POSTGRES_PASSWORD: Bath
      POSTGRES_DB: Bath
    restart: always
    networks:
      - lesson
networks:
  lesson:
